name: 3dunet

channels:
  - conda-forge
  - pytorch

dependencies:
  - python 3.7
  - pytorch
  - torchvision
  - tensorboardx
  - h5py
  - scipy
  - scikit-image
  - scikit-learn
  - pyyaml
  - hdbscan
  - pytest
  - pip:
    - git+https://github.com/bioimage-io/python-bioimage-io#egg=pybio
