manual_seed: 0
model:
  name: UNet2D
  in_channels: 1
  out_channels: 1
  layer_order: gcr
  f_maps: 64
  num_groups: 8
  final_sigmoid: true
  is_segmentation: true
trainer:
  checkpoint_dir: 3dunet
  resume: null
  validate_after_iters: 20
  log_after_iters: 20
  epochs: 100
  iters: 100000
  eval_score_higher_is_better: True
optimizer:
  learning_rate: 0.0002
  weight_decay: 0.00001
loss:
  name: BCEWithLogitsLoss
eval_metric:
  name: DiceCoefficient
lr_scheduler:
  name: ReduceLROnPlateau
  mode: max
  factor: 0.5
  patience: 100
loaders:
  dataset: StandardHDF5Dataset
  batch_size: 8
  num_workers: 8
  raw_internal_path: raw
  label_internal_path: label
  train:
    file_paths:
      - '/home/adrian/workspace/pytorch-3dunet/resources/sample_ovule_2d.h5'

    slice_builder:
      name: SliceBuilder
      patch_shape: [1, 128, 128]
      stride_shape: [1, 32, 32]
      skip_shape_check: true

    transformer:
      raw:
        - name: Standardize
        - name: RandomFlip
        - name: RandomRotate90
        - name: RandomRotate
          axes: [[2, 1]]
          angle_spectrum: 30
          mode: reflect
        - name: ElasticDeformation
          spline_order: 3
        - name: AdditiveGaussianNoise
        - name: AdditivePoissonNoise
        - name: ToTensor
          expand_dims: true
      label:
        - name: RandomFlip
        - name: RandomRotate90
        - name: RandomRotate
          axes: [[2, 1]]
          angle_spectrum: 30
          mode: reflect
        - name: ElasticDeformation
          spline_order: 0
        - name: StandardLabelToBoundary
          blur: true
          sigma: 1.0
        - name: ToTensor
          expand_dims: true
  val:
    file_paths:
      - '../resources/sample_ovule_2d_copy.h5'

    slice_builder:
      name: SliceBuilder
      patch_shape: [1, 128, 128]
      stride_shape: [1, 128, 128]
      skip_shape_check: true

    transformer:
      raw:
        - name: Standardize
        - name: ToTensor
          expand_dims: true
      label:
        - name: StandardLabelToBoundary
          blur: true
          sigma: 1.0
        - name: ToTensor
          expand_dims: true